apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache9-canary-deploy-old
  labels:
    app: apache9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache9
  template:
    metadata:
      name: apachetemplate9
      labels:
        app: apache9
    spec:
      containers:
      - image: httpd
        name: apachecontainer
---
kind: Service
apiVersion: v1
metadata:
  name: apache9-clusteripsvc
spec:
  selector:
    app: apache9
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx9-canary-deploy-new
  labels:
    app: nginx9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx9
  template:
    metadata:
      name: nginxtemplate9
      labels:
        app: nginx9
    spec:
      containers:
      - image: nginx
        name: nginxcontainer
---
kind: Service
apiVersion: v1
metadata:
  name: nginx9-clusteripsvc
spec:
  selector:
    app: nginx9
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
