apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache9-ingresssvc
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache9-clusteripsvc
            port:
              number: 80
